---
- name: Pull Docker Image of Calculator
  hosts: all
  vars:
    ansible_python_interpreter: /Users/riddhichatterjee/opt/anaconda3/bin/python
  tasks:
    - name: Pull image
      docker_image:
        name: riddhich/calculator:latest
        source: pull
    - name: Start docker service
      service:
        name: docker
        state: started
      when: ansible_facts['os_family'] == "Debian"
    - name: Running container
      shell: /usr/local/bin/docker run -it -p 3000:3000 -d riddhich/calculator:latest >> ~/container_id.txt

